plugins {
    id 'net.minecraftforge.gradle' version '7.0.17'
}

evaluationDependsOn(':common')

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraftVersion == '26.1' ? '26.1-62.0.9' : (minecraftVersion == '26.2' ? '26.2-65.1.3' : '26.3-66.0.2')}")
}

minecraft {
    runs {
        register('server') {
            args '--nogui'
        }
    }
}
