plugins {
    id 'java'
}

allprojects {
    apply plugin: 'java'
    
    group = 'dev.demonz.redstonereboot'
    version = '1.6.1'

    repositories {
        mavenCentral()
        maven {
            url = 'https://maven.minecraftforge.net/'
            content {
                includeGroupByRegex 'net\\.minecraftforge(\\..*)?'
                includeGroup 'de.oceanlabs.mcp'
            }
        }
    }

    java {
        toolchain.languageVersion = JavaLanguageVersion.of(21)
        def j21 = JavaVersion.VERSION_21
        sourceCompatibility = project.name == 'neoforge' ? j21 : JavaVersion.VERSION_17
        targetCompatibility = project.name == 'neoforge' ? j21 : JavaVersion.VERSION_17
    }


    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }
}
