plugins {
    id 'net.minecraftforge.gradle' version '6.0.25'
}

repositories {
    maven { url = 'https://maven.minecraftforge.net/' }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.4-49.2.0'
    implementation project(':common')
}

minecraft {
    mappings channel: 'official', version: '1.20.4'
    
    runs {
        server {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'debug'
            args '--nogui'

            mods {
                redstonereboot {
                    source sourceSets.main
                }
            }
        }
    }
}

jar {
    archiveBaseName = 'RedstoneReboot-Forge'
    from(project(':common').sourceSets.main.output) {
        into('/')
    }
}

processResources {
    filesMatching('META-INF/mods.toml') {
        expand(version: project.version)
    }
}
